services:
  redis:
    image: redis:7.0.12
    container_name: redis
    ports: ['6379:6379']
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data

  redis-exporter:
    image: oliver006/redis_exporter:v1.62.0
    container_name: redis_exporter
    command: ['--redis.addr=redis:6379']
    ports: ['9121:9121']
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    ports: ['9090:9090']
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=15d'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - redis-exporter

  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    ports: ['3000:3000']
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_DEFAULT_THEME=dark
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./ops/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  redis-data:
  prometheus-data:
  grafana-storage:
