apiVersion: 1

deleteDatasources:
  - name: Prometheus
    type: prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # ← 用服务名，不要写 localhost
    isDefault: true
    editable: false
